### ISSUE TITLE
[Bug]: one-liner and conhost issue

### ISSUE THREAD

**Issue by uffemcev** [asheroto/winget-install#26]
### What You Are Seeing?

Hello again! :)

So if i use `iex "& { $(iwr asheroto.com/winget) } -Force -ForceClose"` command in Windows Terminal it's restarting in conhost and then it's immediately crash with error: `there are no terminator "@>" in multiline comments`. I can only assume that the problem is formatting, but I'm not sure.

In otherside there is no problem with `&([ScriptBlock]::Create((irm asheroto.com/winget))) -Force -ForceClose` command.

[Video and photo examples](https://drive.google.com/drive/folders/1fyVtT3OrGkW1uqAGBMj6-30pEercoUJq?usp=drive_link). Is it the same for you?

### System Details

Script verson 3.2.2
Windows 11 22H2
UAC disable
Powershell 5.1
Run as administrator

**Comment by asheroto** [comment]
Hello 😊

Indeed that issue is occurring on mine as well. FYI you can simply press `Ctrl+V` while typing here in the Issues to paste in your screenshot or video while in clipboard. You can also drag it inside of the textbox.

I will change the readme to `&([ScriptBlock]::Create((irm asheroto.com/winget))) -Force -ForceClose` as I have no issue with that either. Just a weird quirk I suppose as it's runs normally otherwise.
