### ISSUE TITLE
[Request]: Waiting 5 seconds to exit when winget is already installed is not the best for automated installs

### ISSUE THREAD

**Issue by ben-may** [asheroto/winget-install#34]
### Describe the feature or improvement you're requesting

Waiting 5 seconds to exit when winget is already installed is not the best for automated installs, could we have a parameter to override this?  Not sure why it would need 5 seconds after its essentially done everything?

Thank-you!

**Comment by asheroto** [comment]
Agreed. I will create a new parameter to bypass this.

**Comment by ben-may** [comment]
Thanks!

**Comment by asheroto** [comment]
The original idea behind waiting several seconds is that if people ran it using `Start->Run`, or in another way, it would give the user a few seconds to observe the finished script output. But now that I think about it, this is kind of annoying for most people because many of us probably just use it from the command line and know how to observe the output anyway.

Now the script will not wait by default.

If you want to have the script wait a few seconds, you can specify `-Wait` and it will wait several seconds in order for the user to observe script output.

Thanks for your feedback!

**Comment by ben-may** [comment]
Excellent thank-you, I'm using this latest version now!
