### ISSUE TITLE
[Request]: Non-Zero Exit Code For Console-Host

### ISSUE THREAD

**Issue by AdamDanischewski** [asheroto/winget-install#52]
### Describe the feature or improvement you're requesting

When testing a script that uses winget-install to install winget if not present, I noticed that the captured process has an exit code of 1 not 0 although successful. When looking at the code, it's totally intentional because I'm running it in consolehost not sure why the logic is like this (its my first foray into a PS script) but it looks like Powershell sets the exit code to 1 when you exit via a break statement. 

I'd like your script to return 0 regardless of if I'm launching from consolehost or not. 

Here is the winget-install code:
```
function ExitWithDelay {
...
    # Exit the script with error code
    if ($host.Name -eq 'ConsoleHost') {
        Break
    } else {
        Exit $ExitCode
    }
}

```    
Here is the part where I use it from my code, that I would like to not look for 0,1 yet only 0: 
```
            $wgicmd = Get-Command winget-install | Select-Object -ExpandProperty Definition
            $wgi_cmd_process = Start-Process powershell -Verb RunAs "-Command", "$wgicmd -force -wait" -wait -PassThru
            if ($wgi_cmd_process.ExitCode -in @(0,1)) { 
                Write-host ">> Success, winget is now installed!!" -ForegroundColor Green
            } else { 
                throw "Something went wrong installing winget, exit code: $($wgi_cmd_process.ExitCode)"               
            } 

```

**Comment by asheroto** [comment]
Hey there!

With this last release I updated the code to break instead of exit. The reason for that was that PowerShell kept closing the entire window at the end. So for those running the script locally, breaking would keep the window open, and for scripts running in the background, it would exit with an exit code.

So the challenge is... do we let the script close the PowerShell window but with the right code, or do we let the window remain by breaking but exiting with the wrong exit code.

Ideally I should probably break up the script into additional functions and then run them in order so that the script naturally exits.

As a workaround, I wonder if forcing an error code would work:

```powershell
# Set the exit code after the break
$global:LASTEXITCODE = 0
```

I'll have to test when I get back to my computer.

**Comment by AdamDanischewski** [comment]
Yea I thought that's probably why you wanted to avoid exiting on ConsoleHost, Bash has the same issues. 

You may want to look at the $MyInvocation cmdlet - 
```
if ($MyInvocation.CommandOrigin -eq "Runspace") { 
 break
} ... 

```
_[In testing if it's run directly in the terminal CommandOrigin will be "Internally"]_

**Comment by asheroto** [comment]
Thanks! That worked great. Updating now.

**Comment by uffemcev** [comment]
@asheroto Hello, sorry for late answer. It's that what you need?
![image](https://github.com/user-attachments/assets/54583d8a-d8ab-48f7-b23c-24a87d41782d)

**Comment by asheroto** [comment]
Perfect, thank you! Just wanted to make sure it worked with non-English systems. Looks like they use `Runspace` as well.
